// <auto-generated />
using System;
using BlackJack.Api.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BlackJack.Api.Migrations
{
    [DbContext(typeof(BlackJackContext))]
    partial class BlackJackContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-rtm-30799");

            modelBuilder.Entity("BlackJack.Api.Models.Card", b =>
                {
                    b.Property<long>("CardId")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("DeckfId");

                    b.Property<bool>("IsRevealed");

                    b.Property<int>("Name");

                    b.Property<int>("Suit");

                    b.HasKey("CardId");

                    b.HasIndex("DeckfId");

                    b.ToTable("Card");
                });

            modelBuilder.Entity("BlackJack.Api.Models.Deck", b =>
                {
                    b.Property<long>("DeckId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("DeckName");

                    b.HasKey("DeckId");

                    b.ToTable("Deck");
                });

            modelBuilder.Entity("BlackJack.Api.Models.Game", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long?>("DealerHandDeckId");

                    b.Property<long?>("GameDeckDeckId");

                    b.Property<long?>("GameStatusId");

                    b.Property<long?>("UserHandDeckId");

                    b.HasKey("Id");

                    b.HasIndex("DealerHandDeckId");

                    b.HasIndex("GameDeckDeckId");

                    b.HasIndex("GameStatusId");

                    b.HasIndex("UserHandDeckId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("BlackJack.Api.Models.GameStatus", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CurrentPlayer");

                    b.Property<int>("Winner");

                    b.HasKey("Id");

                    b.ToTable("GameStatus");
                });

            modelBuilder.Entity("BlackJack.Api.Models.Card", b =>
                {
                    b.HasOne("BlackJack.Api.Models.Deck", "Deck")
                        .WithMany("Cards")
                        .HasForeignKey("DeckfId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("BlackJack.Api.Models.Game", b =>
                {
                    b.HasOne("BlackJack.Api.Models.Deck", "DealerHand")
                        .WithMany()
                        .HasForeignKey("DealerHandDeckId");

                    b.HasOne("BlackJack.Api.Models.Deck", "GameDeck")
                        .WithMany()
                        .HasForeignKey("GameDeckDeckId");

                    b.HasOne("BlackJack.Api.Models.GameStatus", "GameStatus")
                        .WithMany()
                        .HasForeignKey("GameStatusId");

                    b.HasOne("BlackJack.Api.Models.Deck", "UserHand")
                        .WithMany()
                        .HasForeignKey("UserHandDeckId");
                });
#pragma warning restore 612, 618
        }
    }
}
